import { ProfileType } from './profile.type';

export const errors: string[] = [
  'cle_interop.structure_invalide',
  'cle_interop.commune_invalide',
  'cle_interop.numero_invalide',
  'voie_nom.valeur_manquante',
  'voie_nom.trop_court',
  'voie_nom.trop_long',
  'voie_nom.caractere_invalide',
  'numero.valeur_manquante',
  'numero.type_invalide',
  'numero.trop_grand',
  'suffixe.debut_invalide',
  'suffixe.trop_long',
  'commune_insee.commune_invalide',
  'x.valeur_invalide',
  'y.valeur_invalide',
  'long.valeur_invalide',
  'lat.valeur_invalide',
  'row.incoherence_numero',
  'row.commune_manquante',
  'row.longlat_vides',
  'row.longlat_invalides',
  'row.adresse_incomplete',
  'field.voie_nom.missing',
  'field.numero.missing',
  'rows.empty',
];

// Les warnings 1.3-relax sont les warnings 1.3 avec les erreurs rajouter dans le 1.3 également
export const warnings: string[] = [
  'cle_interop.voie_invalide',
  'cle_interop.commune_ancienne',
  'voie_nom.casse_incorrecte',
  'voie_nom.contient_tiret_bas',
  'voie_nom_@@.casse_incorrecte',
  'voie_nom_@@.contient_tiret_bas',
  'voie_nom_@@.trop_court',
  'voie_nom_@@.trop_long',
  'voie_nom_@@.caractere_invalide',
  'commune_insee.commune_ancienne',
  'commune_deleguee_insee.commune_invalide',
  'commune_deleguee_insee.commune_non_deleguee',
  'position.enum_fuzzy',
  'position.valeur_invalide',
  'cad_parcelles.valeur_invalide',
  'cad_parcelles.pipe_debut_fin',
  'source.valeur_manquante',
  'date_der_maj.valeur_manquante',
  'date_der_maj.date_ancienne',
  'date_der_maj.date_future',
  'certification_commune.valeur_invalide',
  'row.position_manquante',
  'row.chef_lieu_invalide',
  'row.longlat_xy_incoherents',
  'field.suffixe.missing',
  'field.cle_interop.missing',
  'field.position.missing',
  'field.long.missing',
  'field.lat.missing',
  'field.x.missing',
  'field.y.missing',
  'field.source.missing',
  'field.date_der_maj.missing',
  'field.certification_commune.missing',
  'cle_interop.espaces_debut_fin',
  'commune_nom.espaces_debut_fin',
  'commune_deleguee_insee.espaces_debut_fin',
  'commune_deleguee_nom.espaces_debut_fin',
  'uid_adresse.espaces_debut_fin',
  'voie_nom.espaces_debut_fin',
  'voie_nom_@@.espaces_debut_fin',
  'lieudit_complement_nom.espaces_debut_fin',
  'lieudit_complement_nom_@@.espaces_debut_fin',
  'numero.espaces_debut_fin',
  'position.espaces_debut_fin',
  'long.espaces_debut_fin',
  'lat.espaces_debut_fin',
  'x.espaces_debut_fin',
  'y.espaces_debut_fin',
  'cad_parcelles.espaces_debut_fin',
  'source.espaces_debut_fin',
  'date_der_maj.espaces_debut_fin',
  'uid_adresse.type_invalide',
  'uid_adresse.incoherence_ids_ban',
  'suffixe.caractere_invalide',

  // ERROR IN PROFILE 1.3
  'cle_interop.valeur_manquante',
  'cle_interop.numero_prefixe_manquant',
  'cle_interop.casse_invalide',
  'suffixe.espaces_debut_fin',
  'numero.contient_prefixe',
  'commune_insee.espaces_debut_fin',
  'x.separateur_decimal_invalide',
  'y.separateur_decimal_invalide',
  'long.separateur_decimal_invalide',
  'lat.separateur_decimal_invalide',
  'date_der_maj.date_invalide',
  'field.commune_insee.missing',
  'field.long.missing',
  'field.lat.missing',
  // ERROR IN PROFILE 1.3 NOT WARNING
  // 'commune_insee.valeur_manquante',
  // 'file.encoding.non_standard',
  // 'file.delimiter.non_standard',
  // 'file.linebreak.non_standard',
];

const infos = ['cle_interop.voie_non_renseignee'];

const profile: ProfileType = {
  code: '1.3-relax',
  name: 'BAL 1.3 Relax (legacy)',
  isUsed: false,
  relax: true,
  errors,
  warnings,
  infos,
  format: '1.3',
};

export default profile;
