import { errors as Errors13Relax } from './1.3-relax';
import { ProfileType } from './profile.type';

// Les erreurs du profile 1.3 sont les erreurs 1.3-relax avec quelques unes en plus
export const errors: string[] = [
  ...Errors13Relax,
  // MORE THAN 1.3 RELAX
  'cle_interop.valeur_manquante',
  'cle_interop.numero_prefixe_manquant',
  'cle_interop.casse_invalide',
  'suffixe.espaces_debut_fin',
  'numero.contient_prefixe',
  'commune_insee.valeur_manquante',
  'commune_insee.espaces_debut_fin',
  'x.separateur_decimal_invalide',
  'y.separateur_decimal_invalide',
  'long.separateur_decimal_invalide',
  'lat.separateur_decimal_invalide',
  'date_der_maj.date_invalide',
  'field.commune_insee.missing',
  'field.long.missing',
  'field.lat.missing',
  'file.encoding.non_standard',
  'file.delimiter.non_standard',
  'file.linebreak.non_standard',
];

export const warnings: string[] = [
  'cle_interop.voie_invalide',
  'cle_interop.commune_ancienne',
  'voie_nom.casse_incorrecte',
  'voie_nom.contient_tiret_bas',
  'voie_nom_@@.casse_incorrecte',
  'voie_nom_@@.contient_tiret_bas',
  'voie_nom_@@.trop_court',
  'voie_nom_@@.trop_long',
  'voie_nom_@@.caractere_invalide',
  'commune_insee.commune_ancienne',
  'commune_deleguee_insee.commune_invalide',
  'commune_deleguee_insee.commune_non_deleguee',
  'position.enum_fuzzy',
  'position.valeur_invalide',
  'cad_parcelles.valeur_invalide',
  'cad_parcelles.pipe_debut_fin',
  'source.valeur_manquante',
  'date_der_maj.valeur_manquante',
  'date_der_maj.date_ancienne',
  'date_der_maj.date_future',
  'certification_commune.valeur_invalide',
  'field.suffixe.missing',
  'field.cle_interop.missing',
  'field.position.missing',
  'field.long.missing',
  'field.lat.missing',
  'field.x.missing',
  'field.y.missing',
  'field.source.missing',
  'field.date_der_maj.missing',
  'field.certification_commune.missing',
  'cle_interop.espaces_debut_fin',
  'commune_nom.espaces_debut_fin',
  'commune_deleguee_insee.espaces_debut_fin',
  'commune_deleguee_nom.espaces_debut_fin',
  'uid_adresse.espaces_debut_fin',
  'voie_nom.espaces_debut_fin',
  'voie_nom_@@.espaces_debut_fin',
  'lieudit_complement_nom.espaces_debut_fin',
  'lieudit_complement_nom_@@.espaces_debut_fin',
  'numero.espaces_debut_fin',
  'numero.not_to_be_zero',
  'position.espaces_debut_fin',
  'long.espaces_debut_fin',
  'lat.espaces_debut_fin',
  'x.espaces_debut_fin',
  'y.espaces_debut_fin',
  'cad_parcelles.espaces_debut_fin',
  'source.espaces_debut_fin',
  'date_der_maj.espaces_debut_fin',
  'uid_adresse.type_invalide',
  'uid_adresse.incoherence_ids_ban',
  'row.voie_nom_have_same_lieudit_complement_nom',
  'row.commune_nom_invalide',
  'row.position_manquante',
  'row.chef_lieu_invalide',
  'row.longlat_xy_incoherents',
  'row.coord_outlier',
  'row.cadastre_outlier',
  'row.cadastre_no_exist',
  'row.lieudit_complement_nom_not_declared',
];

const infos = ['cle_interop.voie_non_renseignee'];

const profile: ProfileType = {
  code: '1.3',
  name: 'BAL 1.3 (legacy)',
  isUsed: true,
  relax: false,
  errors,
  warnings,
  infos,
  format: '1.3',
};

export default profile;
